### ISSUE TITLE
Can not install python library for python 3.6.9

### ISSUE THREAD

**Issue by SakibFarhad** [ntop/nDPI#1791]
I am trying to install python bindings for nDPI-4.4.0. but I am getting following errors

OS Version: `CentOS release 6.10 (Final)`
Python Version: `3.6.9`

```bash
[vagrant@centos6-1 python]$ pip install .
Processing /home/vagrant/nDPI-4.4/python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-khg2jha1/setup.py", line 55, in <module>
        'GitHub': 'https://github.com/ntop/nDPI',
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/setuptools/dist.py", line 442, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/setuptools/dist.py", line 601, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/vagrant/dpli-env/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "ndpi/ndpi_build.py", line 89, in <module>
        capture_output=True
      File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
    TypeError: __init__() got an unexpected keyword argument 'capture_output'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-khg2jha1/
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

What did I do?
I installed python `3.6.9` from source as it is not available natively on CentOS 6. 
it works fine. I was able complete following:
```bash
python3.6 -m pip install -r dev_requirements.txt
```

**Comment by aouinizied** [comment]
@SakibFarhad Thanks for reporting, you will need at least python 3.7 for Python bindings.  This will fix your issue.

Zied

**Comment by SakibFarhad** [comment]
I was hoping to use it with `3.6` as this page's [setup.py](https://github.com/ntop/nDPI/tree/dev/python) states to support `3.6`. 
Thanks for your feedback. 
Closing the thread

**Comment by aouinizied** [comment]
Thanks for pointing this out. I fixed it in both the setup.py and the the doc.
