### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#237]
ntopng always crashes when shutting down due to nDPI freeing its resources.

```
(gdb) signal SIGINT
Continuing with signal SIGINT.
28/Jul/2016 10:47:59 [main.cpp:37] Shutting down...
28/Jul/2016 10:47:59 [PcapInterface.cpp:200] Terminated packet polling for en4
28/Jul/2016 10:48:01 [ProtoStats.cpp:35] [IPv4]  1.97 KB/14.00 Packets
28/Jul/2016 10:48:01 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
28/Jul/2016 10:48:01 [ProtoStats.cpp:35] [ARP]   60 B/1.00 Packets
28/Jul/2016 10:48:01 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
28/Jul/2016 10:48:01 [ProtoStats.cpp:35] [Other] 180 B/3.00 Packets
28/Jul/2016 10:48:01 [Ntop.cpp:1304] Interface en4 [running: 0]
28/Jul/2016 10:48:01 [main.cpp:48] Deleted PID /var/run/ntopng.pid [rc: 0]
28/Jul/2016 10:48:01 [NetworkInterface.cpp:397] Flushing host contacts for interface en4
28/Jul/2016 10:48:01 [NetworkInterface.cpp:1570] Cleanup interface en4
ntopng(44362,0x7fff7d532000) malloc: *** error for object 0x384f291: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Program received signal SIGABRT, Aborted.
0x00007fff94eeff06 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
(gdb) bt
#0  0x00007fff94eeff06 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00007fff9302b4ec in pthread_kill () from /usr/lib/system/libsystem_pthread.dylib
#2  0x00007fff982976e7 in abort () from /usr/lib/system/libsystem_c.dylib
#3  0x00007fff902a9041 in free () from /usr/lib/system/libsystem_malloc.dylib
#4  0x00000001000bd4e5 in ndpi_free_automa (_automa=0xb0b <NetworkInterface::get_ndpi_proto_name(unsigned int)+43>) at ndpi_main.c:1805
#5  0x0000000002822e00 in ?? ()
#6  0x00007fff5fbff510 in ?? ()
#7  0x00007fff5fbff618 in ?? ()
#8  0x00007fff5fbff628 in ?? ()
#9  0x00007fff5fbfee00 in ?? ()
#10 0x00000001000661d8 in NetworkInterface::deleteDataStructures (this=0x7fff5fbff628) at src/NetworkInterface.cpp:381
Backtrace stopped: frame did not save the PC
(gdb) f 4
#4  0x00000001000bd4e5 in ndpi_free_automa (_automa=0xb0b <NetworkInterface::get_ndpi_proto_name(unsigned int)+43>) at ndpi_main.c:1805
1805    void ndpi_free_automa(void *_automa)     { ac_automata_release((AC_AUTOMATA_t*)_automa);  }
```

**Comment by kYroL01** [comment]
Thanks @simonemainardi for reporting. I'll check asap.

**Comment by lucaderi** [comment]
@simonemainardi Simone I can't reproduce this issue so I need your help.

**Comment by simonemainardi** [comment]
sorry after cleaning ntopng and ndpi and rebuiling all the error was no longer occurring.
