### ISSUE TITLE
App crash because of nDPI

### ISSUE THREAD

**Issue by andyarus** [ntop/nDPI#440]
nDPI version 1.8
Running app through GDB

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffa19ffb700 (LWP 177668)]
__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:878
878     ../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.
(gdb) bt
#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:878
#1  0x00007ffff6c336da in ndpi_check_http_tcp (flow=<optimized out>, ndpi_struct=0x7ff9f80008c0) at protocols/http.c:844
#2  ndpi_search_http_tcp (ndpi_struct=0x7ff9f80008c0, flow=0x7ff9f8a31c90) at protocols/http.c:1004
#3  0x00007ffff6c275c1 in check_ndpi_tcp_flow_func (ndpi_struct=0x7ff9f80008c0, flow=0x7ff9f8a31c90, ndpi_selection_packet=0x7ffa19ffab38)
    at ndpi_main.c:3244
#4  0x00007ffff6c27c3f in ndpi_detection_process_packet (ndpi_struct=0x7ff9f80008c0, flow=0x7ff9f8a31c90, 
    packet=0x5 <error: Cannot access memory at address 0x5>, packetlen=61664, current_tick_l=3334536704, src=0x7ff9f8a32460, dst=0x7ff9f891a460)
    at ndpi_main.c:3600
```

Any ideas why this happen and how fix this?
It's my mistake or problem in nDPI?
packetlen=61664?
I use buffer length for PF RING zc cluster equal 1536

**Comment by lucaderi** [comment]
Please share the source code of your app as otherwise I cannot help you

**Comment by andyarus** [comment]
```
 ndpi_protocol ndpi_detection_process_packet(struct ndpi_detection_module_struct *ndpi_struct,
					      struct ndpi_flow_struct *flow,
					      const unsigned char *packet,
					      const unsigned short packetlen,
					      const u_int64_t current_tick,
					      struct ndpi_id_struct *src,
					      struct ndpi_id_struct *dst);

packet=0x5 <error: Cannot access memory at address 0x5>
packetlen=61664
```

Seems I get not usual packet bytes and therefore was wrong calculate
```
const unsigned char *packet
const unsigned short packetlen
```

I updated to nDPI 2.0.0 and remade code where I did this calculation and while all works good.
Thanks!
