### ISSUE TITLE
STUN overwrites SSL client certificate

### ISSUE THREAD

**Issue by simonemainardi** [ntop/nDPI#572]
https://github.com/ntop/nDPI/blob/31275398aac0e9862bac831596b8b11a95aae11b/src/lib/protocols/stun.c#L60

Overwrites the second char of the client SSL certificate

**Comment by simonemainardi** [comment]
to reproduce just curl an https resource, .eg., `curl "https://www.digicert.com/ssl/"`

a gdb watch within ntopng helped to find the exact offending line causing the overwrite that is actually due to the stun dissection of already-dissected SSL. Note that the gdb watch alone doesn't bring directly to the offending line (compiler optimizations?). Extra debugging has been necessary to find the exact line posted above.


```
Breakpoint 17, Flow::allocDPIMemory (this=0x7fff9c0045b0) at src/Flow.cpp:146
146	  if((ndpiFlow = (ndpi_flow_struct*)calloc(1, iface->get_flow_size())) == NULL)
(gdb) n
149	  if((cli_id = calloc(1, iface->get_size_id())) == NULL)
(gdb) p &ndpiFlow->protos.ssl.client_certificate[1]
$17 = 0x7fff9c00c369 ""
(gdb) watch  *0x7fff9c00c369
Hardware watchpoint 18: *0x7fff9c00c369
(gdb) c
Continuing.
Hardware watchpoint 18: *0x7fff9c00c369

Old value = 0
New value = 1680766839
0x00007ffff481dd98 in __GI__IO_default_xsputn () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff481dd98 in __GI__IO_default_xsputn () at /lib64/libc.so.6
#1  0x00007ffff47eded3 in vfprintf () at /lib64/libc.so.6
#2  0x00007ffff4818f49 in vsnprintf () at /lib64/libc.so.6
#3  0x00007ffff47f43d2 in snprintf () at /lib64/libc.so.6
#4  0x00000000005162b7 in getSSLcertificate (ndpi_struct=ndpi_struct@entry=0x17bf280, flow=flow@entry=0x7fff9c00c1f0, buffer=buffer@entry=0x7fffa5ff2280 "www.digicert.com", buffer_len=buffer_len@entry=64) at protocols/ssl.c:297
#5  0x0000000000516487 in sslDetectProtocolFromCertificate (ndpi_struct=0x17bf280, flow=0x7fff9c00c1f0) at protocols/ssl.c:370
#6  0x00000000005168ee in ndpi_search_ssl_tcp (ndpi_struct=0x17bf280, flow=0x7fff9c00c1f0) at protocols/ssl.c:651
#7  0x00000000004fb81a in check_ndpi_tcp_flow_func (ndpi_struct=0x17bf280, flow=0x7fff9c00c1f0, ndpi_selection_packet=0x7fffa5ff243c) at ndpi_main.c:3695
#8  0x00000000004fb9c5 in ndpi_detection_process_packet (ndpi_struct=0x17bf280, flow=0x7fff9c00c1f0, packet=<optimized out>, packetlen=<optimized out>, current_tick_l=<optimized out>, src=0x7fff9c00bc30, dst=0x7fff9c00bd50) at ndpi_main.c:4247
#9  0x000000000047051e in NetworkInterface::processPacket(unsigned int, bool, timeval const*, unsigned long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned int, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) (this=0x8ba9d0, bridge_iface_idx=1, ingressPacket=true, when=0x1ad6370, packet_time=1527506910315, eth=0x1ad68a0, vlan_id=0, iph=0x1ad68ae, ip6=0x0, ipsize=248, rawsize=262, h=0x1ad6370, packet=0x1ad68a0 "\004\030\326\061\357Z\f\304z\314Nn\b", ndpiProtocol=0x7fffa5ff2b8e, srcHost=0x7fffa5ff2b80, dstHost=0x7fffa5ff2b78, hostFlow=0x7fffa5ff2b70) at src/NetworkInterface.cpp:1686
#10 0x00000000004722c7 in NetworkInterface::dissectPacket(unsigned int, bool, unsigned char*, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) (this=0x8ba9d0, bridge_iface_idx=1, ingressPacket=true, sender_mac=0x0, h=0x1ad6370, packet=0x1ad68a0 "\004\030\326\061\357Z\f\304z\314Nn\b", ndpiProtocol=0x7fffa5ff2b8e, srcHost=0x7fffa5ff2b80, dstHost=0x7fffa5ff2b78, flow=0x7fffa5ff2b70) at src/NetworkInterface.cpp:2272
#11 0x00000000004437b1 in packetPollLoop(void*) (ptr=0x8ba9d0) at src/PcapInterface.cpp:217
#12 0x00007ffff6d53e25 in start_thread () at /lib64/libpthread.so.0
#13 0x00007ffff489fbad in clone () at /lib64/libc.so.6
(gdb) p  (char)*0x7fff9c00c369
$18 = 119 'w'
(gdb) c
Continuing.
Hardware watchpoint 18: *0x7fff9c00c369

Old value = 1680766839
New value = 1680766840
ndpi_search_stun (ndpi_struct=0x17bf280, flow=0x7fff9c00c1f0) at protocols/stun.c:182
182	       && ((ntohs(get_u_int16_t(packet->payload, 0)) + 2) == packet->payload_packet_len)) {
(gdb)
```
